services:
  jaeger:
    networks:
      backend:
        aliases: [ spm_metrics_source ]
    image: cr.jaegertracing.io/jaegertracing/jaeger:${JAEGER_VERSION:-latest} # Jaeger v2
    volumes:
      - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
      - "./config.yml:/etc/jaeger/config.yml"
    command: ["--config", "/etc/jaeger/config.yml"]
    environment:
      - OTEL_ENABLED=true
    ports:
      - "16686:16686"
      - "8889:8889"
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver, not yet used by Quarkus, optional

  prometheus:
    networks:
      - backend
    image: prom/prometheus:v3.2.1@sha256:6927e0919a144aa7616fd0137d4816816d42f6b816de3af269ab065250859a62
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: changeit
      POSTGRES_USER: pguser
      POSTGRES_DB: test
    ports:
      - '5432:5432'

networks:
  backend:
